# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d900cba477b99fac384af8f36d71ce483c5842f6557b988b191d3ea89636e73298ad92cadd9804efffc6de049ec4b59d50e8428dc94f4fb68edf0ebe05296679

test:
  secret_key_base: a1405f0dd45d82ddcf20cad319f877553dc410a14aacf4c6642262765341d9c69eff2b3f2a693b68b3d17975ea2f8e409a00cddfecc4208223c945ec5a1c7534

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
